In [ ]:
#実践1:
'''y=x^2のある値での傾き(微分)を求める計算式を定義してください。
変化点を小さくすることで算出してください。'''
def f(x):
    return x**2

def derivative(x, delta_x=1e-6):
    return (f(x + delta_x) - f(x)) / delta_x

x = 3
slope = derivative(x)
print(f" y = x^2のx = {x}での傾きは約{slope}です")

 y = x^2のx = 3での傾きは6.000001000927568です


# 新しいセクション

In [ ]:
#実践２
'''任意の関数を受け取ってその関数の傾き(微分)を求める計算式を関数で定義してください。'''

def derivative(func, delta_x=1e-6):
    return (func(x + delta_x) - func(x)) / delta_x


In [ ]:
#実践3-1:行列演算
'''以下の演算を実施してください。
ベクトル同士の足し算・引き算
(a) 足し算: u = (2, -3, 5),
v = (-1, 4, 1)
u + vを計算せよ。'''

import numpy as np
u = np.array([2, -3, 5]),
v = np.array([-1, 4, 1])
print("ベクトル同士の足し算・引き算")
print(f"(a){u+v}")

'''(b) 引き算:
x = (7, -2, 4),
y = (3, 5, -1)
x - yを計算せよ。'''

x = np.array([7, -2, 4]),
y = np.array([3, 5, -1])
print(f"(b){x-y}")

'''行列同士の足し算引き算'''
'''(a)'''
A = np.array([[1,2,0], [3,-1,4]])
B = np.array([[4,1,2],[-2,3,1]])

print("行列同士の足し算引き算")
print(f"(a){A+B}")

'''(b) '''
C = np.array([[5,7,2],[-3,4,6],[1,-2,3]])
D = np.array([[2,-1,4],[6,3,-2],[-4,1,5]])
print(f"(b){C-D}")

'''ベクトルのスカラー倍
u = (2, -5, 3)
2uを計算せよ。'''

u = (2, -5, 3)
print("ベクトルのスカラー倍")
print(f"2u={u *2}")



'''行列のスカラー倍
-3Aを計算せよ。'''

A2 = np.array([[1,4,2], [3,-2,5]])

print("行列のスカラー倍")
print(f"-3A = {-3*A2}")

'''ABを計算せよ。'''

A3 = np.array([[2,1], [3,4], [5,2]])
B3 = np.array([[6,2], [2,7]])

print(f"AB = {np.dot(A3, B3)}")

'''行列とベクトルの掛け算

Auを計算せよ。'''

A4= np.array([[1,2,3], [4,5,6]])
u = np.array([2,3,1])

print("行列とベクトルの掛け算")
print(f"Au = {np.dot(A4,u)}")

'''行列と単位行列の掛け算
AI3を計算せよ。(I3は3×3の単位行列)'''

A5 = np.array([[2,3,1], [4,0,2], [5,6,7]])
I = 1
print("行列と単位行列の掛け算")
print(f"AI3 = {A5*I}")

ベクトル同士の足し算・引き算
(a)[[1 1 6]]
(b)[[ 4 -7  5]]
行列同士の足し算引き算
(a)[[5 3 2]
 [1 2 5]]
(b)[[ 3  8 -2]
 [-9  1  8]
 [ 5 -3 -2]]
ベクトルのスカラー倍
2u=(2, -5, 3, 2, -5, 3)
行列のスカラー倍
-3A = [[ -3 -12  -6]
 [ -9   6 -15]]
AB = [[14 11]
 [26 34]
 [34 24]]
行列とベクトルの掛け算
Au = [11 29]
行列と単位行列の掛け算
AI3 = [[2 3 1]
 [4 0 2]
 [5 6 7]]


In [ ]:
#実践4-1(統計)
'''サンプルデータ 生徒10人の数学とプログラミングの試験点数が以下のように与えられています。
数学: [75, 82, 91, 64, 88, 73, 95, 67, 81, 70]
プログラミング: [85, 76, 92, 68, 79, 81, 88, 65, 73, 87]
問題1: 平均値を求める 数学とプログラミングの試験点数それぞれの平均点を求めてください。'''

from math import sqrt

math_scores = [75, 82, 91, 64, 88, 73, 95, 67, 81, 70]
prog_scores = [85, 76, 92, 68, 79, 81, 88, 65, 73, 87]

def mean(scores):
    return sum(scores)/len(scores)

math_mean = mean(math_scores)
prog_mean = mean(prog_scores)
print(f"数学の平均点: {math_mean}")
print(f"プログラミングの平均点: {prog_mean}")

# 問題2: 中央値
def median(scores):
    sorted_scores = sorted(scores)
    n = len(sorted_scores)
    if n % 2 == 1:
        return sorted_scores[n // 2]
    else:
        right = n // 2
        left = right - 1
        return (sorted_scores[left] + sorted_scores[right]) / 2

math_median = median(math_scores)
prog_median = median(prog_scores)
print(f"数学の中央値: {math_median}")
print(f"プログラミングの中央値: {prog_median}")

# 問題3: 最頻値
def mode(scores):
    count = {}
    for score in scores:
        count[score] = count.get(score, 0) + 1

    max_count = max(count.values())
    max_score = []
    for key, value in count.items():
         if value == max_count:
            max_score.append(key)
    if len(max_score) == len(count):
        return list(count.keys())
    elif len(max_score) == 1:
        return max_score[0]

math_mode = mode(math_scores)
prog_mode = mode(prog_scores)
print(f"数学の最頻値: {math_mode}")
print(f"プログラミングの最頻値: {prog_mode}")


# 問題4: 標準偏差と分散
def stdev(scores):
    mean_val = mean(scores)
    import math
    variance = sum((x - mean_val) ** 2 for x in scores) / len(scores)
    return math.sqrt(variance)

def variance(scores):
    mean_val = mean(scores)
    return sum((score - mean_val) ** 2 for score in scores) / len(scores)


math_std = stdev(math_scores)
prog_std = stdev(prog_scores)
math_var = variance(math_scores)
prog_var = variance(prog_scores)
print(f"数学の標準偏差: {math_std}")
print(f"プログラミングの標準偏差: {prog_std}")
print(f"数学の分散: {math_var}")
print(f"プログラミングの分散: {prog_var}")


# 問題5: 相関係数(応用: 数式を確認する必要がある)
def covariance(x, y):
    x_mean = mean(x)
    y_mean = mean(y)
    cov = sum((x_i - x_mean) * (y_i - y_mean) for x_i, y_i in zip(x, y))
    return cov / (len(x) - 1)

def corr_coef(x, y):
    return covariance(x, y)/(stdev(x)*stdev(y))

corr = corr_coef(math_scores, prog_scores)
print(f"数学とプログラミングの相関係数: {corr}")

数学の平均点: 78.6
プログラミングの平均点: 79.4
数学の中央値: 78.0
プログラミングの中央値: 80.0
数学の最頻値: [75, 82, 91, 64, 88, 73, 95, 67, 81, 70]
プログラミングの最頻値: [85, 76, 92, 68, 79, 81, 88, 65, 73, 87]
数学の標準偏差: 9.971960689854328
プログラミングの標準偏差: 8.452218643646175
数学の分散: 99.44
プログラミングの分散: 71.44
数学とプログラミングの相関係数: 0.6665201372516742



実践4-2
標準正規分布について調べて報告してください。正規分布との違いは何ですか？


標準正規分布は、平均が0で標準偏差が1の正規分布を指します。正規分布と標準正規分布の主な違いは、平均と標準偏差の値です。

実践4-3(応用):
二項分布・ポアソン分布・指数分布・ベルヌーイ分布・幾何分布について調べて報告してください。

二項分布 (Binomial Distribution):
二項分布は、2つの結果のうち1つを成功として定義し、それぞれの成功確率が同じである独立なベルヌーイ試行をn回行った場合の成功回数の確率分布です。

ポアソン分布 (Poisson Distribution):
ポアソン分布は、ある一定の時間や領域で発生するイベントの回数が、平均的に一定の率で起こるときに、その回数の確率分布を表します。
例：単位時間あたりの交通事故の発生数など

指数分布 (Exponential Distribution):
指数分布は、ある事象が起こるまでの時間間隔が従う確率分布です。
例：あるイベントが発生するまでの待ち時間や製品の寿命など

ベルヌーイ分布 (Bernoulli Distribution):
ベルヌーイ分布は、2つの結果（例えば成功と失敗）を持つ試行の確率分布です。
例:コインを5回投げた時に表2回出る確率

幾何分布 (Geometric Distribution):
幾何分布は、ベルヌーイ試行で初めて成功が起こるまでの失敗の回数（試行回数）の確率分布です。
例:1の目が出るまでにサイコロを振り続ける回数の分布



実践5-1(回帰)
最小二乗法について説明してください。

最小二乗法は、「予測モデルによる予測値」と「実測値」の誤差を2乗した和を最小化する手法です。誤差の2乗の和を最小化するような予測モデルのパラメータを特定し、予測モデルを実測値にフィットさせます

実践5-2:
過学習について説明してください。 過学習が起きると何が問題でしょうか。

過学習（Overfitting）は、機械学習や統計モデリングにおいて、モデルが訓練データに過度に適合しすぎる現象を指します。

過学習が起きると、モデルが訓練データに対して過度に適合するため、新しいデータに対してうまく予測できなくなります。つまり、モデルが訓練データに適合しすぎてしまうため、本来の目的である未知のデータに対する予測能力が低下します。


In [ ]:
#実践5-4:
'''以下の決定係数の算出問題を計算してください。

データセット

x (年収/万円): 300, 400, 500, 600, 700

y (支出額/万円): 150, 220, 300, 380, 420

以下のサンプルコードを埋めてください。'''


import math

# データ
x = [300, 400, 500, 600, 700]
y = [150, 220, 300, 380, 420]
n = len(x)

# 平均値
x_mean = sum(x) / n
y_mean = sum(y) / n

# 直線の係数 a, b (最小二乗法)
numer = sum((x_i - x_mean) * (y_i - y_mean) for x_i, y_i in zip(x, y))
denom = sum((x_i - x_mean) ** 2 for x_i in x)
a = numer / denom
b = y_mean - a * x_mean

# 予測値
y_pred = [a * x_i + b for x_i in x]

# 決定係数
ss_res = sum((y_i - y_pred_i) for y_i, y_pred_i in zip(y, y_pred)) ** 2
ss_tot = sum((y_i - y_mean) ** 2 for y_i in y)
r_squared = 1 - (ss_res / ss_tot)

print(f"直線の係数: a = {a}, b = {b}")
print(f"決定係数 R^2 = {r_squared}")

直線の係数: a = 0.7, b = -56.0
決定係数 R^2 = 1.0


In [ ]:
#実践5-5
'''単回帰と重回帰の違いを数式を例にして説明してください。'''

単回帰は、1つの要素()から数値を予測するモデルであること
　y=ax+b

・重回帰は、複数の要素から数値を予測するモデルであること
y=a1x1+a2x2​+⋯+anxn+b

In [ ]:
#実践5-6
'''リッジ回帰・ラッソ回帰・elastic-netの違いについて調べて報告してください。
例えば説明変数の数が多い場合はどの手法を使うべきでしょうか？'''

Ridge回帰は重みの2乗和に制約を課しています。これによって影響度の少ない要素の重みを抑え、過学習を抑制します。
LASSO回帰は、重みの絶対値の和に制約を課します。一部の特徴量のみが重要なとき、Lasso回帰を、
全ての特徴量が重要だが、過学習を防ぎたいときはRidge回帰を使用する良いらしい。
elastic-netは両方のいい所を合わせたもの。



In [ ]:
## 実践6-1(分類: 混同行列/評価指標の定義)
'''以下の実際のラベル値と予測値が与えられています。混同行列、Recall、Precision、F値をそれぞれ計算してください。ライブラリは使わず手計算で行ってその結果を記載してください。

補足) Recall=再現率, Precision=適合率

実際のラベル値: [1, 0, 1, 1, 0, 1, 0, 1, 0, 0]

予測値: [1, 1, 0, 1, 0, 0, 1, 1, 0, 0]'''

Rcall:0.4
Precision:0.6
F値:0.48

In [ ]:
#実践6-2 (応用)
'''不純度はGini不純度とエントロピーが代表的です。
エントロピーについて概要を調べてみてください。'''

エントロピーは、データの不確実性や混乱度を測定するための重要な指標で、
エントロピーを最小化するようにデータを分割することで、より純度の高いノードを作成できます。
決定木は過学習しやすいモデルです。ジニ不純度とエントロピーを使用して適切な分割を行うことで、
過度に複雑なツリー構造を避け、より一般化されたモデルを構築できます。



In [ ]:
#実践6-3
'''木構造で過学習を防ぐ方法としてどんな方法がありますか？'''
木構造の深さに上限を設ける
木構造の葉（条件分岐の最も先の部分）の枚数に上限を設ける
葉のデータ数に最小値を設ける

In [ ]:
#実践6-4(応用)
'''上記説明でのGini不純度の計算をPythonを用いて計算してみてください。

Gini不純度の計算方法を関数として定義して計算ください。'''

def gini_impurity(pass_count: int, fail_count: int) -> float:
    """
    Calculate the Gini impurity for a binary classification problem.

    Args:
        pass_count (int): The number of passing instances.
        fail_count (int): The number of failing instances.

    Returns:
        float: The Gini impurity value.
    """
    total_count = pass_count + fail_count
    if total_count == 0:
        return 0
    p_pass = pass_count / total_count
    p_fail = fail_count / total_count
    return 1 - (p_pass ** 2 + p_fail ** 2)

over_10h = gini_impurity (4,2)
print(f"10h以上の勉強での不純度＝{over_10h}")



10h以上の勉強での不純度＝0.4444444444444444


In [ ]:
#実践7-1(クラスタリング): 応用
'''調査問題1: クラスタリングアルゴリズムの種類と特徴'
クラスタリングにはどのようなアルゴリズムがあるか調べてみましょう。代表的なアルゴリズムの種類、概要、利点・欠点をまとめてください'''

クラスタリングの種類は、グルーピング方法の違いで「非階層的クラスタリング」と「階層的クラスタリング」に大別。
・非階層的クラスタリング
「非階層的クラスタリング」とは、階層を作らず、単にグループ分けをするクラスタリングのこと。
母集団の中で近いデータをまとめ、事前に指定されたクラスタ数に分割。
非階層的クラスタリングにはk-means法、混合正規分布の2つの方法がある

・階層的クラスタリング
階層的クラスタリングは、観測値同士がどのくらい似ているかを「距離」とした場合、距離の近さごとにクラスタをまとめていく手法。
グループ化していく過程は「樹形図（デンドログラム：dendrogram）」で表現でき、可視化される点が特徴です。
ウォード法, 群平均法, 最短（最長）距離法

k-means
最初に指定したクラスタの数だけ「重心」をランダムに指定し、その重心を基準にクラスタを分けていくという手法
＜長所＞
・階層型クラスター分析よりも計算量が少なく、サンプルサイズが比較的大きなデータを分類するのに適している
＜短所＞
・クラスタ数を事前に決める必要がある
・重心の初期値によって結果が変わる
・外れ値やノイズの影響を受けやすい

ウォード法
ウォード法は、それぞれのデータの平方和（それぞれのデータと平均値の差を二乗した値の和）を求め、
平方和が小さなものからクラスタを作っていく手法。
平方和はデータのばらつきを表す。
＜長所＞
バランスよくデータを分類することが可能で、階層クラスタリングの中ではよく使われる手法。
分析したいデータに応じた計算方法を選ぶことが重要ですが、「迷ったらウォード法」と言われるほど、ウォード法はバラつきを抑えた分析が可能。
＜短所＞
計算量が多い

群平均法
群平均法では、2つのクラスタを構成するデータのすべての組み合わせの距離を求め、その平均をクラスタ間の距離とする手法
＜長所＞
クラスタ内に外れ値があったとしても影響を受けにくい
ウォード法に比べると計算量が少ない
＜短所＞
ウォード法より精度が劣ることが多い

最短距離法
最短距離法は、2つのクラスタ間で一番近いデータ同士の距離を、クラスタ間の距離として採用する手法
＜長所＞
ウォード法に比べると計算量が少ない
＜短所＞
クラスタ内に外れ値があった場合、最短距離法では鎖効果が出やすくなり、分類感度が低くなってしまう

最長距離法
最長距離法は最短距離法とは逆の手法で、クラスタを構成する要素同士のすべての距離の中で最長のものを、クラスタ間の距離として採用。
＜長所＞
ウォード法に比べると計算量が少ない
＜短所＞
クラスタ内に外れ値があった場合、最短距離法では鎖効果が出やすくなり、分類感度が低くなってしまう

'''調査問題2: 距離尺度の種類と使い分けクラスタリングでは、データ点間の類似性を測る尺度が必要です。
様々な距離尺度があるので、代表的な距離尺度とその特徴、使い分けをまとめてください。'''

距離尺度は、データの性質やクラスタリングの目的に応じて選択する必要がある
ユークリッド距離 (Euclidean Distance)
＜特徴＞
二点間の直線距離を測定。

マンハッタン距離 (Manhattan Distance)
＜特徴＞
データ点間の軸に沿った距離を測定

コサイン類似度 (Cosine Similarity)
＜特徴＞
二つのベクトル間の角度の余弦値を測定。

ジャッカード距離 (Jaccard Distance)
＜特徴＞
二つの集合間の非類似度を測定。集合の交わりの割合を考慮

ハミング距離 (Hamming Distance)
＜特徴＞
二つの同じ長さの文字列間の異なる位置の個数を測定

マハラノビス距離
＜特徴＞
データの分散共分散行列を考慮して距離を測定

使い分け
ユークリッド距離やマンハッタン距離は数値データに適しており、コサイン類似度はテキストデータや高次元スパースデータに有効。
ジャッカード距離やハミング距離は質的データやバイナリデータに適す。
マハラノビス距離は異なるスケールや相関を持つデータに対して有効。データの特性を理解し
、適切な距離尺度を選ぶことで、効果的なクラスタリングが可能

'''調査問題3: 質的データのクラスタリング
これまでは数値データを扱いましたが、質的データ(カテゴリデータ)をクラスタリングする方法も考えられます。
質的データをクラスタリングする際の工夫点や注意点を調べてみましょう。'''

質的データのクラスタリングにおける工夫点・注意点
1. 適切な距離尺度の選択
質的データのクラスタリングでは、データの性質に適した距離尺度を選択することが重要。

質的データでよく使用される距離尺度
ジャッカード係数: 二つの集合間の類似度を測定し。バイナリデータやカテゴリカルデータに適す。
ハミング距離: 二つの文字列間の異なる位置の個数を測定。バイナリデータに適す。

2. データの前処理
質的データをクラスタリングする前に、データの前処理が必要。

エンコーディング: 質的データを数値データに変換する方法として、ワンホットエンコーディングやラベルエンコーディングがある。
ワンホットエンコーディングは、カテゴリ間の距離を均等に保つために有効。

3. クラスタ数の選定
質的データのクラスタ数を選定する際には、以下の方法が有効。
シルエットスコア: 各データポイントのクラスタリングの良さを評価します。
エルボー法: クラスタ数に対するコスト関数の変化をグラフにプロットし、膝点（エルボー）を見つける方法です。

'''調査問題4: クラスタリング評価指標
クラスタリング結果の良し悪しを評価する指標があります。
代表的な評価指標とその概要、利用シーンをまとめてください。'''

シルエット係数
シルエット係数は、各データポイントのクラスタリングの品質を評価する指標。
スコアは -1 から 1 の範囲を取り、1 に近いほど良いクラスタリングを示す。
＜利用シーン＞
クラスタリングアルゴリズムのパフォーマンスを比較する際に使用。
クラスタ数を決定する際の参考としても用いられる。

ダビーズ・ボウルダイン基準
クラスタのコンパクトさとクラスタ間の分離を評価する指標。
＜利用シーン＞
複数のクラスタリング結果を比較する際に使用。
クラスタ数の決定にも役立つ。

Calinski Harabasz基準
WSSに対するクラスター間の分散（データセットの重心からすべてのクラスターの重心の分散）の割合
＜利用シーン＞
最適なクラスター数を評価

Inertia
クラスタ内のサンプルとクラスタ中心の距離の二乗和を表す指標
＜利用シーン＞
K-meansクラスタリングの最適なクラスタ数を決定する際に使用。
エルボー法と組み合わせて、適切なクラスタ数を視覚的に確認。



'''調査問題5: クラスタリングの実践的な利用例
クラスタリングはどのような分野で利用されているか、実践的な利用例を調べてみましょう。
マーケティング、画像処理、自然言語処理などの具体例を挙げてください。'''

＜マーケティング＞
顧客セグメンテーション
顧客を異なるグループに分類し、それぞれのグループに対して
最適なマーケティング戦略を立てるために利用されます。
例
ターゲットマーケティング: 顧客データ（購買履歴、行動パターン、デモグラフィック情報など）をクラスタリングし、
特定の製品やキャンペーンに最適なターゲットグループを見つける。
小売業、eコマース、金融サービスなど、顧客データを大量に持つ業界で広く利用されています。

＜画像処理＞
画像セグメンテーション
画像を意味のある部分に分割し、異なるオブジェクトや領域を識別するために利用されます。

例
医用画像処理: MRIやCTスキャンの画像をクラスタリングし、腫瘍や異常部分を識別する。
顔認識: 顔画像をクラスタリングして、異なる表情や照明条件に対応する。
医療分野、監視システム、自動運転車など、精度の高い画像認識が必要な分野で活用されています。


＜自然言語処理 (NLP)＞
テキストクラスタリング
文書やテキストデータをクラスタリングし、類似した内容のものをグループ化するために利用されます。
例
トピックモデリング: ニュース記事、論文、ソーシャルメディアの投稿などをクラスタリングし、異なるトピックに分類する。
チャットボット: 類似した問い合わせをグループ化し、効率的な応答を生成する。
利用シーン:
情報検索、コンテンツフィルタリング、カスタマーサポートなど、テキストデータの整理と分析が重要な領域で使用されています。