In [ ]:
#実践1:
'''y=x^2のある値での傾き(微分)を求める計算式を定義してください。
変化点を小さくすることで算出してください。'''
def f(x):
    return x**2

def derivative(x, delta_x=1e-6):
    return (f(x + delta_x) - f(x)) / delta_x

x = 3
slope = derivative(x)
print(f" y = x^2のx = {x}での傾きは約{slope}です")

 y = x^2のx = 3での傾きは6.000001000927568です


# 新しいセクション

In [ ]:
#実践２
'''任意の関数を受け取ってその関数の傾き(微分)を求める計算式を関数で定義してください。'''

def derivative(func, delta_x=1e-6):
    return (func(x + delta_x) - func(x)) / delta_x


In [ ]:
#実践3-1:行列演算
'''以下の演算を実施してください。
ベクトル同士の足し算・引き算
(a) 足し算: u = (2, -3, 5),
v = (-1, 4, 1)
u + vを計算せよ。'''

import numpy as np
u = np.array([2, -3, 5]),
v = np.array([-1, 4, 1])
print("ベクトル同士の足し算・引き算")
print(f"(a){u+v}")

'''(b) 引き算:
x = (7, -2, 4),
y = (3, 5, -1)
x - yを計算せよ。'''

x = np.array([7, -2, 4]),
y = np.array([3, 5, -1])
print(f"(b){x-y}")

'''行列同士の足し算引き算'''
'''(a)'''
A = np.array([[1,2,0], [3,-1,4]])
B = np.array([[4,1,2],[-2,3,1]])

print("行列同士の足し算引き算")
print(f"(a){A+B}")

'''(b) '''
C = np.array([[5,7,2],[-3,4,6],[1,-2,3]])
D = np.array([[2,-1,4],[6,3,-2],[-4,1,5]])
print(f"(b){C-D}")

'''ベクトルのスカラー倍
u = (2, -5, 3)
2uを計算せよ。'''

u = (2, -5, 3)
print("ベクトルのスカラー倍")
print(f"2u={u *2}")



'''行列のスカラー倍
-3Aを計算せよ。'''

A2 = np.array([[1,4,2], [3,-2,5]])

print("行列のスカラー倍")
print(f"-3A = {-3*A2}")

'''ABを計算せよ。'''

A3 = np.array([[2,1], [3,4], [5,2]])
B3 = np.array([[6,2], [2,7]])

print(f"AB = {np.dot(A3, B3)}")

'''行列とベクトルの掛け算

Auを計算せよ。'''

A4= np.array([[1,2,3], [4,5,6]])
u = np.array([2,3,1])

print("行列とベクトルの掛け算")
print(f"Au = {np.dot(A4,u)}")

'''行列と単位行列の掛け算
AI3を計算せよ。(I3は3×3の単位行列)'''

A5 = np.array([[2,3,1], [4,0,2], [5,6,7]])
I = 1
print("行列と単位行列の掛け算")
print(f"AI3 = {A5*I}")

ベクトル同士の足し算・引き算
(a)[[1 1 6]]
(b)[[ 4 -7  5]]
行列同士の足し算引き算
(a)[[5 3 2]
 [1 2 5]]
(b)[[ 3  8 -2]
 [-9  1  8]
 [ 5 -3 -2]]
ベクトルのスカラー倍
2u=(2, -5, 3, 2, -5, 3)
行列のスカラー倍
-3A = [[ -3 -12  -6]
 [ -9   6 -15]]
AB = [[14 11]
 [26 34]
 [34 24]]
行列とベクトルの掛け算
Au = [11 29]
行列と単位行列の掛け算
AI3 = [[2 3 1]
 [4 0 2]
 [5 6 7]]


In [ ]:
#実践4-1(統計)
'''サンプルデータ 生徒10人の数学とプログラミングの試験点数が以下のように与えられています。
数学: [75, 82, 91, 64, 88, 73, 95, 67, 81, 70]
プログラミング: [85, 76, 92, 68, 79, 81, 88, 65, 73, 87]
問題1: 平均値を求める 数学とプログラミングの試験点数それぞれの平均点を求めてください。'''

from math import sqrt

math_scores = [75, 82, 91, 64, 88, 73, 95, 67, 81, 70]
prog_scores = [85, 76, 92, 68, 79, 81, 88, 65, 73, 87]

def mean(scores):
    return sum(scores)/len(scores)

math_mean = mean(math_scores)
prog_mean = mean(prog_scores)
print(f"数学の平均点: {math_mean}")
print(f"プログラミングの平均点: {prog_mean}")

# 問題2: 中央値
def median(scores):
    sorted_scores = sorted(scores)
    n = len(sorted_scores)
    if n % 2 == 1:
        return sorted_scores[n // 2]
    else:
        right = n // 2
        left = right - 1
        return (sorted_scores[left] + sorted_scores[right]) / 2

math_median = median(math_scores)
prog_median = median(prog_scores)
print(f"数学の中央値: {math_median}")
print(f"プログラミングの中央値: {prog_median}")

# 問題3: 最頻値
def mode(scores):
    count = {}
    for score in scores:
        count[score] = count.get(score, 0) + 1

    max_count = max(count.values())
    max_score = []
    for key, value in count.items():
         if value == max_count:
            max_score.append(key)
    if len(max_score) == len(count):
        return list(count.keys())
    elif len(max_score) == 1:
        return max_score[0]

math_mode = mode(math_scores)
prog_mode = mode(prog_scores)
print(f"数学の最頻値: {math_mode}")
print(f"プログラミングの最頻値: {prog_mode}")


# 問題4: 標準偏差と分散
def stdev(scores):
    mean_val = mean(scores)
    import math
    variance = sum((x - mean_val) ** 2 for x in scores) / len(scores)
    return math.sqrt(variance)

def variance(scores):
    mean_val = mean(scores)
    return sum((score - mean_val) ** 2 for score in scores) / len(scores)


math_std = stdev(math_scores)
prog_std = stdev(prog_scores)
math_var = variance(math_scores)
prog_var = variance(prog_scores)
print(f"数学の標準偏差: {math_std}")
print(f"プログラミングの標準偏差: {prog_std}")
print(f"数学の分散: {math_var}")
print(f"プログラミングの分散: {prog_var}")


# 問題5: 相関係数(応用: 数式を確認する必要がある)
def covariance(x, y):
    x_mean = mean(x)
    y_mean = mean(y)
    cov = sum((x_i - x_mean) * (y_i - y_mean) for x_i, y_i in zip(x, y))
    return cov / (len(x) - 1)

def corr_coef(x, y):
    return covariance(x, y)/(stdev(x)*stdev(y))

corr = corr_coef(math_scores, prog_scores)
print(f"数学とプログラミングの相関係数: {corr}")

数学の平均点: 78.6
プログラミングの平均点: 79.4
数学の中央値: 78.0
プログラミングの中央値: 80.0
数学の最頻値: [75, 82, 91, 64, 88, 73, 95, 67, 81, 70]
プログラミングの最頻値: [85, 76, 92, 68, 79, 81, 88, 65, 73, 87]
数学の標準偏差: 9.971960689854328
プログラミングの標準偏差: 8.452218643646175
数学の分散: 99.44
プログラミングの分散: 71.44
数学とプログラミングの相関係数: 0.6665201372516742



実践4-2
標準正規分布について調べて報告してください。正規分布との違いは何ですか？


標準正規分布は、平均が0で標準偏差が1の正規分布を指します。正規分布と標準正規分布の主な違いは、平均と標準偏差の値です。

実践4-3(応用):
二項分布・ポアソン分布・指数分布・ベルヌーイ分布・幾何分布について調べて報告してください。

二項分布 (Binomial Distribution):
二項分布は、2つの結果のうち1つを成功として定義し、それぞれの成功確率が同じである独立なベルヌーイ試行をn回行った場合の成功回数の確率分布です。

ポアソン分布 (Poisson Distribution):
ポアソン分布は、ある一定の時間や領域で発生するイベントの回数が、平均的に一定の率で起こるときに、その回数の確率分布を表します。
例：単位時間あたりの交通事故の発生数など

指数分布 (Exponential Distribution):
指数分布は、ある事象が起こるまでの時間間隔が従う確率分布です。
例：あるイベントが発生するまでの待ち時間や製品の寿命など

ベルヌーイ分布 (Bernoulli Distribution):
ベルヌーイ分布は、2つの結果（例えば成功と失敗）を持つ試行の確率分布です。
例:コインを5回投げた時に表2回出る確率

幾何分布 (Geometric Distribution):
幾何分布は、ベルヌーイ試行で初めて成功が起こるまでの失敗の回数（試行回数）の確率分布です。
例:1の目が出るまでにサイコロを振り続ける回数の分布



実践5-1(回帰)
最小二乗法について説明してください。

最小二乗法は、「予測モデルによる予測値」と「実測値」の誤差を2乗した和を最小化する手法です。誤差の2乗の和を最小化するような予測モデルのパラメータを特定し、予測モデルを実測値にフィットさせます

実践5-2:
過学習について説明してください。 過学習が起きると何が問題でしょうか。

過学習（Overfitting）は、機械学習や統計モデリングにおいて、モデルが訓練データに過度に適合しすぎる現象を指します。

過学習が起きると、モデルが訓練データに対して過度に適合するため、新しいデータに対してうまく予測できなくなります。つまり、モデルが訓練データに適合しすぎてしまうため、本来の目的である未知のデータに対する予測能力が低下します。
